name: Github Rebot for Sealos
on:
  issue_comment:
    types:
      - created
env:
  GH_TOKEN: "${{ secrets.GH_PAT }}"
jobs:
  comment:
    if: startswith(github.event.comment.body, '/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Using gh-rebot
        uses: labring/gh-rebot@v0.0.6-rc1
        env:
          SEALOS_TYPE: "/comment"
