name: Github Rebot for Sealos test comment
on:
  issue_comment:
    types:
      - created
jobs:
  comment:
    if: startswith(github.event.comment.body, '/xx')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - uses: labring/gh-rebot@v0.0.6-rc6
        if: ${{ (github.event_name != 'push') }}
        with:
          version: v0.0.6-rc6
        env:
          SEALOS_TYPE: "/comment"
          GH_TOKEN: "${{ secrets.GH_PAT }}"
